//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.24 at 11:58:45 PM CEST 
//


package no.smeaworks.movies.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AudioTrackType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AudioTrackType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AudioContent" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AudioFormat" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AudioChannels" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AudioTrackType", propOrder = {
    "audioContent",
    "audioFormat",
    "audioChannels"
})
public class AudioTrackType {

    @XmlElement(name = "AudioContent", required = true)
    protected String audioContent;
    @XmlElement(name = "AudioFormat", required = true)
    protected String audioFormat;
    @XmlElement(name = "AudioChannels", required = true)
    protected String audioChannels;

    /**
     * Gets the value of the audioContent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAudioContent() {
        return audioContent;
    }

    /**
     * Sets the value of the audioContent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAudioContent(String value) {
        this.audioContent = value;
    }

    /**
     * Gets the value of the audioFormat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAudioFormat() {
        return audioFormat;
    }

    /**
     * Sets the value of the audioFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAudioFormat(String value) {
        this.audioFormat = value;
    }

    /**
     * Gets the value of the audioChannels property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAudioChannels() {
        return audioChannels;
    }

    /**
     * Sets the value of the audioChannels property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAudioChannels(String value) {
        this.audioChannels = value;
    }

}
