//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.24 at 11:58:45 PM CEST 
//


package no.smeaworks.movies.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ColorFormatType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ColorFormatType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ClrColor">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="true"/>
 *               &lt;enumeration value="false"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ClrBlackAndWhite">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="false"/>
 *               &lt;enumeration value="true"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ClrColorized" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ClrMixed">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="false"/>
 *               &lt;enumeration value="true"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ColorFormatType", propOrder = {
    "clrColor",
    "clrBlackAndWhite",
    "clrColorized",
    "clrMixed"
})
public class ColorFormatType {

    @XmlElement(name = "ClrColor", required = true)
    protected String clrColor;
    @XmlElement(name = "ClrBlackAndWhite", required = true)
    protected String clrBlackAndWhite;
    @XmlElement(name = "ClrColorized", required = true)
    protected String clrColorized;
    @XmlElement(name = "ClrMixed", required = true)
    protected String clrMixed;

    /**
     * Gets the value of the clrColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClrColor() {
        return clrColor;
    }

    /**
     * Sets the value of the clrColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClrColor(String value) {
        this.clrColor = value;
    }

    /**
     * Gets the value of the clrBlackAndWhite property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClrBlackAndWhite() {
        return clrBlackAndWhite;
    }

    /**
     * Sets the value of the clrBlackAndWhite property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClrBlackAndWhite(String value) {
        this.clrBlackAndWhite = value;
    }

    /**
     * Gets the value of the clrColorized property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClrColorized() {
        return clrColorized;
    }

    /**
     * Sets the value of the clrColorized property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClrColorized(String value) {
        this.clrColorized = value;
    }

    /**
     * Gets the value of the clrMixed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClrMixed() {
        return clrMixed;
    }

    /**
     * Sets the value of the clrMixed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClrMixed(String value) {
        this.clrMixed = value;
    }

}
