//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.24 at 11:58:45 PM CEST 
//


package no.smeaworks.movies.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DimensionsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DimensionsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Dim2D">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="true"/>
 *               &lt;enumeration value="false"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Dim3DAnaglyph" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Dim3DBluRay">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="false"/>
 *               &lt;enumeration value="true"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DimensionsType", propOrder = {
    "dim2D",
    "dim3DAnaglyph",
    "dim3DBluRay"
})
public class DimensionsType {

    @XmlElement(name = "Dim2D", required = true)
    protected String dim2D;
    @XmlElement(name = "Dim3DAnaglyph", required = true)
    protected String dim3DAnaglyph;
    @XmlElement(name = "Dim3DBluRay", required = true)
    protected String dim3DBluRay;

    /**
     * Gets the value of the dim2D property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDim2D() {
        return dim2D;
    }

    /**
     * Sets the value of the dim2D property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDim2D(String value) {
        this.dim2D = value;
    }

    /**
     * Gets the value of the dim3DAnaglyph property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDim3DAnaglyph() {
        return dim3DAnaglyph;
    }

    /**
     * Sets the value of the dim3DAnaglyph property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDim3DAnaglyph(String value) {
        this.dim3DAnaglyph = value;
    }

    /**
     * Gets the value of the dim3DBluRay property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDim3DBluRay() {
        return dim3DBluRay;
    }

    /**
     * Sets the value of the dim3DBluRay property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDim3DBluRay(String value) {
        this.dim3DBluRay = value;
    }

}
