//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.24 at 11:58:45 PM CEST 
//


package no.smeaworks.movies.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DiscType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DiscType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DescriptionSideA" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DescriptionSideB">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value=""/>
 *               &lt;enumeration value="Main Feature"/>
 *               &lt;enumeration value="Main Feature (Part 2)"/>
 *               &lt;enumeration value="Episode 3-6"/>
 *               &lt;enumeration value="Episode 11-14"/>
 *               &lt;enumeration value="Episode 19-22"/>
 *               &lt;enumeration value="Episode 3-4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DiscIDSideA" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DiscIDSideB">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value=""/>
 *               &lt;enumeration value="D554C729002AD9DB"/>
 *               &lt;enumeration value="E38645439A531AED"/>
 *               &lt;enumeration value="52944BC5088CA7F8"/>
 *               &lt;enumeration value="0DE256B0AA9A42CF"/>
 *               &lt;enumeration value="C6476FD6A4974ED8"/>
 *               &lt;enumeration value="231ED7A55C874844"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="LabelSideA" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="LabelSideB">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value=""/>
 *               &lt;enumeration value="GETTYSBURG"/>
 *               &lt;enumeration value="GODS_AND_GENERALS_SIDE_B"/>
 *               &lt;enumeration value="ER_SEASON_1_DISC_1"/>
 *               &lt;enumeration value="ER_SEASON_1_DISC_2B"/>
 *               &lt;enumeration value="ER_SEASON_1_DISC_3B"/>
 *               &lt;enumeration value="SOPRANOS_SEASON3_DISC1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DualLayeredSideA">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="false"/>
 *               &lt;enumeration value="true"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DualLayeredSideB">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="false"/>
 *               &lt;enumeration value="true"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DualSided">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="false"/>
 *               &lt;enumeration value="true"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Location" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Slot" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DiscType", propOrder = {
    "descriptionSideA",
    "descriptionSideB",
    "discIDSideA",
    "discIDSideB",
    "labelSideA",
    "labelSideB",
    "dualLayeredSideA",
    "dualLayeredSideB",
    "dualSided",
    "location",
    "slot"
})
public class DiscType {

    @XmlElement(name = "DescriptionSideA", required = true)
    protected String descriptionSideA;
    @XmlElement(name = "DescriptionSideB", required = true)
    protected String descriptionSideB;
    @XmlElement(name = "DiscIDSideA", required = true)
    protected String discIDSideA;
    @XmlElement(name = "DiscIDSideB", required = true)
    protected String discIDSideB;
    @XmlElement(name = "LabelSideA", required = true)
    protected String labelSideA;
    @XmlElement(name = "LabelSideB", required = true)
    protected String labelSideB;
    @XmlElement(name = "DualLayeredSideA", required = true)
    protected String dualLayeredSideA;
    @XmlElement(name = "DualLayeredSideB", required = true)
    protected String dualLayeredSideB;
    @XmlElement(name = "DualSided", required = true)
    protected String dualSided;
    @XmlElement(name = "Location", required = true)
    protected String location;
    @XmlElement(name = "Slot", required = true)
    protected String slot;

    /**
     * Gets the value of the descriptionSideA property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescriptionSideA() {
        return descriptionSideA;
    }

    /**
     * Sets the value of the descriptionSideA property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescriptionSideA(String value) {
        this.descriptionSideA = value;
    }

    /**
     * Gets the value of the descriptionSideB property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescriptionSideB() {
        return descriptionSideB;
    }

    /**
     * Sets the value of the descriptionSideB property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescriptionSideB(String value) {
        this.descriptionSideB = value;
    }

    /**
     * Gets the value of the discIDSideA property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiscIDSideA() {
        return discIDSideA;
    }

    /**
     * Sets the value of the discIDSideA property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiscIDSideA(String value) {
        this.discIDSideA = value;
    }

    /**
     * Gets the value of the discIDSideB property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiscIDSideB() {
        return discIDSideB;
    }

    /**
     * Sets the value of the discIDSideB property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiscIDSideB(String value) {
        this.discIDSideB = value;
    }

    /**
     * Gets the value of the labelSideA property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabelSideA() {
        return labelSideA;
    }

    /**
     * Sets the value of the labelSideA property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabelSideA(String value) {
        this.labelSideA = value;
    }

    /**
     * Gets the value of the labelSideB property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabelSideB() {
        return labelSideB;
    }

    /**
     * Sets the value of the labelSideB property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabelSideB(String value) {
        this.labelSideB = value;
    }

    /**
     * Gets the value of the dualLayeredSideA property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDualLayeredSideA() {
        return dualLayeredSideA;
    }

    /**
     * Sets the value of the dualLayeredSideA property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDualLayeredSideA(String value) {
        this.dualLayeredSideA = value;
    }

    /**
     * Gets the value of the dualLayeredSideB property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDualLayeredSideB() {
        return dualLayeredSideB;
    }

    /**
     * Sets the value of the dualLayeredSideB property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDualLayeredSideB(String value) {
        this.dualLayeredSideB = value;
    }

    /**
     * Gets the value of the dualSided property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDualSided() {
        return dualSided;
    }

    /**
     * Sets the value of the dualSided property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDualSided(String value) {
        this.dualSided = value;
    }

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocation(String value) {
        this.location = value;
    }

    /**
     * Gets the value of the slot property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSlot() {
        return slot;
    }

    /**
     * Sets the value of the slot property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSlot(String value) {
        this.slot = value;
    }

}
