//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.24 at 11:58:45 PM CEST 
//


package no.smeaworks.movies.jaxb;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for DVDType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DVDType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ProfileTimestamp" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ID_Base" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ID_VariantNum">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}byte">
 *               &lt;enumeration value="0"/>
 *               &lt;enumeration value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ID_LocalityID">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}byte">
 *               &lt;enumeration value="0"/>
 *               &lt;enumeration value="12"/>
 *               &lt;enumeration value="5"/>
 *               &lt;enumeration value="4"/>
 *               &lt;enumeration value="16"/>
 *               &lt;enumeration value="14"/>
 *               &lt;enumeration value="11"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ID_LocalityDesc">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="United States"/>
 *               &lt;enumeration value="Norway"/>
 *               &lt;enumeration value="Germany"/>
 *               &lt;enumeration value="United Kingdom"/>
 *               &lt;enumeration value="Finland"/>
 *               &lt;enumeration value="Denmark"/>
 *               &lt;enumeration value="Sweden"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ID_Type">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="UPCEAN"/>
 *               &lt;enumeration value="DiscID"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="MediaTypes" type="{}MediaTypesType"/>
 *         &lt;element name="UPC" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CollectionNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CollectionType" type="{}CollectionTypeType"/>
 *         &lt;element name="Title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DistTrait" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OriginalTitle" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CountryOfOrigin" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CountryOfOrigin2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CountryOfOrigin3" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ProductionYear" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="Released" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="RunningTime" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="RatingSystem" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Film"/>
 *               &lt;enumeration value="Television"/>
 *               &lt;enumeration value="Film &amp; Television"/>
 *               &lt;enumeration value="Ikärajat 2001-2011, tarkastetut"/>
 *               &lt;enumeration value="Film (2015+)"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Rating" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RatingAge" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="RatingVariant">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}byte">
 *               &lt;enumeration value="0"/>
 *               &lt;enumeration value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="RatingDetails" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CaseType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CaseSlipCover" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Genres" type="{}GenresType"/>
 *         &lt;element name="Regions">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Region" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="1"/>
 *                         &lt;enumeration value="A"/>
 *                         &lt;enumeration value="B"/>
 *                         &lt;enumeration value="2"/>
 *                         &lt;enumeration value="4"/>
 *                         &lt;enumeration value="5"/>
 *                         &lt;enumeration value="C"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Format" type="{}FormatType"/>
 *         &lt;element name="Features" type="{}FeaturesType"/>
 *         &lt;element name="Studios" type="{}StudiosType"/>
 *         &lt;element name="MediaCompanies" type="{}MediaCompaniesType"/>
 *         &lt;element name="Audio" type="{}AudioType"/>
 *         &lt;element name="Subtitles" type="{}SubtitlesType"/>
 *         &lt;element name="SRP" type="{}SRPType"/>
 *         &lt;element name="Discs" type="{}DiscsType"/>
 *         &lt;element name="SortTitle" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="LastEdited" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="WishPriority">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}byte">
 *               &lt;enumeration value="0"/>
 *               &lt;enumeration value="5"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="CountAs">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}byte">
 *               &lt;enumeration value="1"/>
 *               &lt;enumeration value="0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PurchaseInfo" type="{}PurchaseInfoType"/>
 *         &lt;element name="Review" type="{}ReviewType"/>
 *         &lt;element name="MediaBanners" type="{}MediaBannersType"/>
 *         &lt;element name="Events">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Event" type="{}EventType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="BoxSet" type="{}BoxSetType"/>
 *         &lt;element name="LoanInfo" type="{}LoanInfoType"/>
 *         &lt;element name="MyLinks" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DVDType", propOrder = {
    "profileTimestamp",
    "id",
    "idBase",
    "idVariantNum",
    "idLocalityID",
    "idLocalityDesc",
    "idType",
    "mediaTypes",
    "upc",
    "collectionNumber",
    "collectionType",
    "title",
    "distTrait",
    "originalTitle",
    "countryOfOrigin",
    "countryOfOrigin2",
    "countryOfOrigin3",
    "productionYear",
    "released",
    "runningTime",
    "ratingSystem",
    "rating",
    "ratingAge",
    "ratingVariant",
    "ratingDetails",
    "caseType",
    "caseSlipCover",
    "genres",
    "regions",
    "format",
    "features",
    "studios",
    "mediaCompanies",
    "audio",
    "subtitles",
    "srp",
    "discs",
    "sortTitle",
    "lastEdited",
    "wishPriority",
    "countAs",
    "purchaseInfo",
    "review",
    "mediaBanners",
    "events",
    "boxSet",
    "loanInfo",
    "myLinks"
})
public class DVDType {

    @XmlElement(name = "ProfileTimestamp", required = true)
    protected String profileTimestamp;
    @XmlElement(name = "ID", required = true)
    protected String id;
    @XmlElement(name = "ID_Base", required = true)
    protected String idBase;
    @XmlElement(name = "ID_VariantNum")
    protected byte idVariantNum;
    @XmlElement(name = "ID_LocalityID")
    protected byte idLocalityID;
    @XmlElement(name = "ID_LocalityDesc", required = true)
    protected String idLocalityDesc;
    @XmlElement(name = "ID_Type", required = true)
    protected String idType;
    @XmlElement(name = "MediaTypes", required = true)
    protected MediaTypesType mediaTypes;
    @XmlElement(name = "UPC", required = true)
    protected String upc;
    @XmlElement(name = "CollectionNumber", required = true)
    protected String collectionNumber;
    @XmlElement(name = "CollectionType", required = true)
    protected CollectionTypeType collectionType;
    @XmlElement(name = "Title", required = true)
    protected String title;
    @XmlElement(name = "DistTrait", required = true)
    protected String distTrait;
    @XmlElement(name = "OriginalTitle", required = true)
    protected String originalTitle;
    @XmlElement(name = "CountryOfOrigin", required = true)
    protected String countryOfOrigin;
    @XmlElement(name = "CountryOfOrigin2", required = true)
    protected String countryOfOrigin2;
    @XmlElement(name = "CountryOfOrigin3", required = true)
    protected String countryOfOrigin3;
    @XmlElement(name = "ProductionYear")
    protected short productionYear;
    @XmlElement(name = "Released")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar released;
    @XmlElement(name = "RunningTime")
    protected short runningTime;
    @XmlElement(name = "RatingSystem")
    protected String ratingSystem;
    @XmlElement(name = "Rating", required = true)
    protected String rating;
    @XmlElement(name = "RatingAge")
    protected byte ratingAge;
    @XmlElement(name = "RatingVariant")
    protected byte ratingVariant;
    @XmlElement(name = "RatingDetails")
    protected String ratingDetails;
    @XmlElement(name = "CaseType", required = true)
    protected String caseType;
    @XmlElement(name = "CaseSlipCover")
    protected String caseSlipCover;
    @XmlElement(name = "Genres", required = true)
    protected GenresType genres;
    @XmlElement(name = "Regions", required = true)
    protected DVDType.Regions regions;
    @XmlElement(name = "Format", required = true)
    protected FormatType format;
    @XmlElement(name = "Features", required = true)
    protected FeaturesType features;
    @XmlElement(name = "Studios", required = true)
    protected StudiosType studios;
    @XmlElement(name = "MediaCompanies", required = true)
    protected MediaCompaniesType mediaCompanies;
    @XmlElement(name = "Audio", required = true)
    protected AudioType audio;
    @XmlElement(name = "Subtitles", required = true)
    protected SubtitlesType subtitles;
    @XmlElement(name = "SRP", required = true)
    protected SRPType srp;
    @XmlElement(name = "Discs", required = true)
    protected DiscsType discs;
    @XmlElement(name = "SortTitle", required = true)
    protected String sortTitle;
    @XmlElement(name = "LastEdited", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lastEdited;
    @XmlElement(name = "WishPriority")
    protected byte wishPriority;
    @XmlElement(name = "CountAs")
    protected byte countAs;
    @XmlElement(name = "PurchaseInfo", required = true)
    protected PurchaseInfoType purchaseInfo;
    @XmlElement(name = "Review", required = true)
    protected ReviewType review;
    @XmlElement(name = "MediaBanners", required = true)
    protected MediaBannersType mediaBanners;
    @XmlElement(name = "Events", required = true)
    protected DVDType.Events events;
    @XmlElement(name = "BoxSet", required = true)
    protected BoxSetType boxSet;
    @XmlElement(name = "LoanInfo", required = true)
    protected LoanInfoType loanInfo;
    @XmlElement(name = "MyLinks", required = true)
    protected String myLinks;

    /**
     * Gets the value of the profileTimestamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProfileTimestamp() {
        return profileTimestamp;
    }

    /**
     * Sets the value of the profileTimestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProfileTimestamp(String value) {
        this.profileTimestamp = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the idBase property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIDBase() {
        return idBase;
    }

    /**
     * Sets the value of the idBase property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIDBase(String value) {
        this.idBase = value;
    }

    /**
     * Gets the value of the idVariantNum property.
     * 
     */
    public byte getIDVariantNum() {
        return idVariantNum;
    }

    /**
     * Sets the value of the idVariantNum property.
     * 
     */
    public void setIDVariantNum(byte value) {
        this.idVariantNum = value;
    }

    /**
     * Gets the value of the idLocalityID property.
     * 
     */
    public byte getIDLocalityID() {
        return idLocalityID;
    }

    /**
     * Sets the value of the idLocalityID property.
     * 
     */
    public void setIDLocalityID(byte value) {
        this.idLocalityID = value;
    }

    /**
     * Gets the value of the idLocalityDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIDLocalityDesc() {
        return idLocalityDesc;
    }

    /**
     * Sets the value of the idLocalityDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIDLocalityDesc(String value) {
        this.idLocalityDesc = value;
    }

    /**
     * Gets the value of the idType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIDType() {
        return idType;
    }

    /**
     * Sets the value of the idType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIDType(String value) {
        this.idType = value;
    }

    /**
     * Gets the value of the mediaTypes property.
     * 
     * @return
     *     possible object is
     *     {@link MediaTypesType }
     *     
     */
    public MediaTypesType getMediaTypes() {
        return mediaTypes;
    }

    /**
     * Sets the value of the mediaTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link MediaTypesType }
     *     
     */
    public void setMediaTypes(MediaTypesType value) {
        this.mediaTypes = value;
    }

    /**
     * Gets the value of the upc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUPC() {
        return upc;
    }

    /**
     * Sets the value of the upc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUPC(String value) {
        this.upc = value;
    }

    /**
     * Gets the value of the collectionNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCollectionNumber() {
        return collectionNumber;
    }

    /**
     * Sets the value of the collectionNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCollectionNumber(String value) {
        this.collectionNumber = value;
    }

    /**
     * Gets the value of the collectionType property.
     * 
     * @return
     *     possible object is
     *     {@link CollectionTypeType }
     *     
     */
    public CollectionTypeType getCollectionType() {
        return collectionType;
    }

    /**
     * Sets the value of the collectionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link CollectionTypeType }
     *     
     */
    public void setCollectionType(CollectionTypeType value) {
        this.collectionType = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the distTrait property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDistTrait() {
        return distTrait;
    }

    /**
     * Sets the value of the distTrait property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDistTrait(String value) {
        this.distTrait = value;
    }

    /**
     * Gets the value of the originalTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginalTitle() {
        return originalTitle;
    }

    /**
     * Sets the value of the originalTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginalTitle(String value) {
        this.originalTitle = value;
    }

    /**
     * Gets the value of the countryOfOrigin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryOfOrigin() {
        return countryOfOrigin;
    }

    /**
     * Sets the value of the countryOfOrigin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryOfOrigin(String value) {
        this.countryOfOrigin = value;
    }

    /**
     * Gets the value of the countryOfOrigin2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryOfOrigin2() {
        return countryOfOrigin2;
    }

    /**
     * Sets the value of the countryOfOrigin2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryOfOrigin2(String value) {
        this.countryOfOrigin2 = value;
    }

    /**
     * Gets the value of the countryOfOrigin3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryOfOrigin3() {
        return countryOfOrigin3;
    }

    /**
     * Sets the value of the countryOfOrigin3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryOfOrigin3(String value) {
        this.countryOfOrigin3 = value;
    }

    /**
     * Gets the value of the productionYear property.
     * 
     */
    public short getProductionYear() {
        return productionYear;
    }

    /**
     * Sets the value of the productionYear property.
     * 
     */
    public void setProductionYear(short value) {
        this.productionYear = value;
    }

    /**
     * Gets the value of the released property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getReleased() {
        return released;
    }

    /**
     * Sets the value of the released property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setReleased(XMLGregorianCalendar value) {
        this.released = value;
    }

    /**
     * Gets the value of the runningTime property.
     * 
     */
    public short getRunningTime() {
        return runningTime;
    }

    /**
     * Sets the value of the runningTime property.
     * 
     */
    public void setRunningTime(short value) {
        this.runningTime = value;
    }

    /**
     * Gets the value of the ratingSystem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRatingSystem() {
        return ratingSystem;
    }

    /**
     * Sets the value of the ratingSystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRatingSystem(String value) {
        this.ratingSystem = value;
    }

    /**
     * Gets the value of the rating property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRating() {
        return rating;
    }

    /**
     * Sets the value of the rating property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRating(String value) {
        this.rating = value;
    }

    /**
     * Gets the value of the ratingAge property.
     * 
     */
    public byte getRatingAge() {
        return ratingAge;
    }

    /**
     * Sets the value of the ratingAge property.
     * 
     */
    public void setRatingAge(byte value) {
        this.ratingAge = value;
    }

    /**
     * Gets the value of the ratingVariant property.
     * 
     */
    public byte getRatingVariant() {
        return ratingVariant;
    }

    /**
     * Sets the value of the ratingVariant property.
     * 
     */
    public void setRatingVariant(byte value) {
        this.ratingVariant = value;
    }

    /**
     * Gets the value of the ratingDetails property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRatingDetails() {
        return ratingDetails;
    }

    /**
     * Sets the value of the ratingDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRatingDetails(String value) {
        this.ratingDetails = value;
    }

    /**
     * Gets the value of the caseType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCaseType() {
        return caseType;
    }

    /**
     * Sets the value of the caseType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCaseType(String value) {
        this.caseType = value;
    }

    /**
     * Gets the value of the caseSlipCover property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCaseSlipCover() {
        return caseSlipCover;
    }

    /**
     * Sets the value of the caseSlipCover property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCaseSlipCover(String value) {
        this.caseSlipCover = value;
    }

    /**
     * Gets the value of the genres property.
     * 
     * @return
     *     possible object is
     *     {@link GenresType }
     *     
     */
    public GenresType getGenres() {
        return genres;
    }

    /**
     * Sets the value of the genres property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenresType }
     *     
     */
    public void setGenres(GenresType value) {
        this.genres = value;
    }

    /**
     * Gets the value of the regions property.
     * 
     * @return
     *     possible object is
     *     {@link DVDType.Regions }
     *     
     */
    public DVDType.Regions getRegions() {
        return regions;
    }

    /**
     * Sets the value of the regions property.
     * 
     * @param value
     *     allowed object is
     *     {@link DVDType.Regions }
     *     
     */
    public void setRegions(DVDType.Regions value) {
        this.regions = value;
    }

    /**
     * Gets the value of the format property.
     * 
     * @return
     *     possible object is
     *     {@link FormatType }
     *     
     */
    public FormatType getFormat() {
        return format;
    }

    /**
     * Sets the value of the format property.
     * 
     * @param value
     *     allowed object is
     *     {@link FormatType }
     *     
     */
    public void setFormat(FormatType value) {
        this.format = value;
    }

    /**
     * Gets the value of the features property.
     * 
     * @return
     *     possible object is
     *     {@link FeaturesType }
     *     
     */
    public FeaturesType getFeatures() {
        return features;
    }

    /**
     * Sets the value of the features property.
     * 
     * @param value
     *     allowed object is
     *     {@link FeaturesType }
     *     
     */
    public void setFeatures(FeaturesType value) {
        this.features = value;
    }

    /**
     * Gets the value of the studios property.
     * 
     * @return
     *     possible object is
     *     {@link StudiosType }
     *     
     */
    public StudiosType getStudios() {
        return studios;
    }

    /**
     * Sets the value of the studios property.
     * 
     * @param value
     *     allowed object is
     *     {@link StudiosType }
     *     
     */
    public void setStudios(StudiosType value) {
        this.studios = value;
    }

    /**
     * Gets the value of the mediaCompanies property.
     * 
     * @return
     *     possible object is
     *     {@link MediaCompaniesType }
     *     
     */
    public MediaCompaniesType getMediaCompanies() {
        return mediaCompanies;
    }

    /**
     * Sets the value of the mediaCompanies property.
     * 
     * @param value
     *     allowed object is
     *     {@link MediaCompaniesType }
     *     
     */
    public void setMediaCompanies(MediaCompaniesType value) {
        this.mediaCompanies = value;
    }

    /**
     * Gets the value of the audio property.
     * 
     * @return
     *     possible object is
     *     {@link AudioType }
     *     
     */
    public AudioType getAudio() {
        return audio;
    }

    /**
     * Sets the value of the audio property.
     * 
     * @param value
     *     allowed object is
     *     {@link AudioType }
     *     
     */
    public void setAudio(AudioType value) {
        this.audio = value;
    }

    /**
     * Gets the value of the subtitles property.
     * 
     * @return
     *     possible object is
     *     {@link SubtitlesType }
     *     
     */
    public SubtitlesType getSubtitles() {
        return subtitles;
    }

    /**
     * Sets the value of the subtitles property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubtitlesType }
     *     
     */
    public void setSubtitles(SubtitlesType value) {
        this.subtitles = value;
    }

    /**
     * Gets the value of the srp property.
     * 
     * @return
     *     possible object is
     *     {@link SRPType }
     *     
     */
    public SRPType getSRP() {
        return srp;
    }

    /**
     * Sets the value of the srp property.
     * 
     * @param value
     *     allowed object is
     *     {@link SRPType }
     *     
     */
    public void setSRP(SRPType value) {
        this.srp = value;
    }

    /**
     * Gets the value of the discs property.
     * 
     * @return
     *     possible object is
     *     {@link DiscsType }
     *     
     */
    public DiscsType getDiscs() {
        return discs;
    }

    /**
     * Sets the value of the discs property.
     * 
     * @param value
     *     allowed object is
     *     {@link DiscsType }
     *     
     */
    public void setDiscs(DiscsType value) {
        this.discs = value;
    }

    /**
     * Gets the value of the sortTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSortTitle() {
        return sortTitle;
    }

    /**
     * Sets the value of the sortTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSortTitle(String value) {
        this.sortTitle = value;
    }

    /**
     * Gets the value of the lastEdited property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastEdited() {
        return lastEdited;
    }

    /**
     * Sets the value of the lastEdited property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastEdited(XMLGregorianCalendar value) {
        this.lastEdited = value;
    }

    /**
     * Gets the value of the wishPriority property.
     * 
     */
    public byte getWishPriority() {
        return wishPriority;
    }

    /**
     * Sets the value of the wishPriority property.
     * 
     */
    public void setWishPriority(byte value) {
        this.wishPriority = value;
    }

    /**
     * Gets the value of the countAs property.
     * 
     */
    public byte getCountAs() {
        return countAs;
    }

    /**
     * Sets the value of the countAs property.
     * 
     */
    public void setCountAs(byte value) {
        this.countAs = value;
    }

    /**
     * Gets the value of the purchaseInfo property.
     * 
     * @return
     *     possible object is
     *     {@link PurchaseInfoType }
     *     
     */
    public PurchaseInfoType getPurchaseInfo() {
        return purchaseInfo;
    }

    /**
     * Sets the value of the purchaseInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link PurchaseInfoType }
     *     
     */
    public void setPurchaseInfo(PurchaseInfoType value) {
        this.purchaseInfo = value;
    }

    /**
     * Gets the value of the review property.
     * 
     * @return
     *     possible object is
     *     {@link ReviewType }
     *     
     */
    public ReviewType getReview() {
        return review;
    }

    /**
     * Sets the value of the review property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReviewType }
     *     
     */
    public void setReview(ReviewType value) {
        this.review = value;
    }

    /**
     * Gets the value of the mediaBanners property.
     * 
     * @return
     *     possible object is
     *     {@link MediaBannersType }
     *     
     */
    public MediaBannersType getMediaBanners() {
        return mediaBanners;
    }

    /**
     * Sets the value of the mediaBanners property.
     * 
     * @param value
     *     allowed object is
     *     {@link MediaBannersType }
     *     
     */
    public void setMediaBanners(MediaBannersType value) {
        this.mediaBanners = value;
    }

    /**
     * Gets the value of the events property.
     * 
     * @return
     *     possible object is
     *     {@link DVDType.Events }
     *     
     */
    public DVDType.Events getEvents() {
        return events;
    }

    /**
     * Sets the value of the events property.
     * 
     * @param value
     *     allowed object is
     *     {@link DVDType.Events }
     *     
     */
    public void setEvents(DVDType.Events value) {
        this.events = value;
    }

    /**
     * Gets the value of the boxSet property.
     * 
     * @return
     *     possible object is
     *     {@link BoxSetType }
     *     
     */
    public BoxSetType getBoxSet() {
        return boxSet;
    }

    /**
     * Sets the value of the boxSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link BoxSetType }
     *     
     */
    public void setBoxSet(BoxSetType value) {
        this.boxSet = value;
    }

    /**
     * Gets the value of the loanInfo property.
     * 
     * @return
     *     possible object is
     *     {@link LoanInfoType }
     *     
     */
    public LoanInfoType getLoanInfo() {
        return loanInfo;
    }

    /**
     * Sets the value of the loanInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link LoanInfoType }
     *     
     */
    public void setLoanInfo(LoanInfoType value) {
        this.loanInfo = value;
    }

    /**
     * Gets the value of the myLinks property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMyLinks() {
        return myLinks;
    }

    /**
     * Sets the value of the myLinks property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMyLinks(String value) {
        this.myLinks = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Event" type="{}EventType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "content"
    })
    public static class Events {

        @XmlElementRef(name = "Event", type = JAXBElement.class, required = false)
        @XmlMixed
        protected List<Serializable> content;

        /**
         * Gets the value of the content property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the content property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getContent().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link JAXBElement }{@code <}{@link EventType }{@code >}
         * {@link String }
         * 
         * 
         */
        public List<Serializable> getContent() {
            if (content == null) {
                content = new ArrayList<Serializable>();
            }
            return this.content;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Region" maxOccurs="unbounded" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="1"/>
     *               &lt;enumeration value="A"/>
     *               &lt;enumeration value="B"/>
     *               &lt;enumeration value="2"/>
     *               &lt;enumeration value="4"/>
     *               &lt;enumeration value="5"/>
     *               &lt;enumeration value="C"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "content"
    })
    public static class Regions {

        @XmlElementRef(name = "Region", type = JAXBElement.class, required = false)
        @XmlMixed
        protected List<Serializable> content;

        /**
         * Gets the value of the content property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the content property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getContent().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * {@link String }
         * 
         * 
         */
        public List<Serializable> getContent() {
            if (content == null) {
                content = new ArrayList<Serializable>();
            }
            return this.content;
        }

    }

}
