//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.24 at 11:58:45 PM CEST 
//


package no.smeaworks.movies.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DynamicRangeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DynamicRangeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DRHDR10">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="true"/>
 *               &lt;enumeration value="false"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DRDolbyVision">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="false"/>
 *               &lt;enumeration value="true"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DynamicRangeType", propOrder = {
    "drhdr10",
    "drDolbyVision"
})
public class DynamicRangeType {

    @XmlElement(name = "DRHDR10", required = true)
    protected String drhdr10;
    @XmlElement(name = "DRDolbyVision", required = true)
    protected String drDolbyVision;

    /**
     * Gets the value of the drhdr10 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDRHDR10() {
        return drhdr10;
    }

    /**
     * Sets the value of the drhdr10 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDRHDR10(String value) {
        this.drhdr10 = value;
    }

    /**
     * Gets the value of the drDolbyVision property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDRDolbyVision() {
        return drDolbyVision;
    }

    /**
     * Sets the value of the drDolbyVision property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDRDolbyVision(String value) {
        this.drDolbyVision = value;
    }

}
