//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.24 at 11:58:45 PM CEST 
//


package no.smeaworks.movies.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FeaturesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FeaturesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FeatureSceneAccess">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="true"/>
 *               &lt;enumeration value="false"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="FeatureCommentary">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="false"/>
 *               &lt;enumeration value="true"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="FeatureTrailer">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="false"/>
 *               &lt;enumeration value="true"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="FeaturePhotoGallery">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="false"/>
 *               &lt;enumeration value="true"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="FeatureDeletedScenes">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="false"/>
 *               &lt;enumeration value="true"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="FeatureMakingOf">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="false"/>
 *               &lt;enumeration value="true"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="FeatureProductionNotes">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="false"/>
 *               &lt;enumeration value="true"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="FeatureGame">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="false"/>
 *               &lt;enumeration value="true"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="FeatureDVDROMContent">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="false"/>
 *               &lt;enumeration value="true"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="FeatureMultiAngle">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="false"/>
 *               &lt;enumeration value="true"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="FeatureMusicVideos">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="false"/>
 *               &lt;enumeration value="true"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="FeatureInterviews">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="false"/>
 *               &lt;enumeration value="true"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="FeatureStoryboardComparisons">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="false"/>
 *               &lt;enumeration value="true"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="FeatureOuttakes">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="false"/>
 *               &lt;enumeration value="true"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="FeatureClosedCaptioned">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="false"/>
 *               &lt;enumeration value="true"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="FeatureTHXCertified">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="false"/>
 *               &lt;enumeration value="true"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="FeaturePIP">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="false"/>
 *               &lt;enumeration value="true"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="FeatureBDLive">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="false"/>
 *               &lt;enumeration value="true"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="FeatureBonusTrailers">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="true"/>
 *               &lt;enumeration value="false"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="FeatureDigitalCopy">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="false"/>
 *               &lt;enumeration value="true"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="FeatureDBOX">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="false"/>
 *               &lt;enumeration value="true"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="FeatureCineChat">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="false"/>
 *               &lt;enumeration value="true"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="FeaturePlayAll">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="false"/>
 *               &lt;enumeration value="true"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="FeatureMovieIQ">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="false"/>
 *               &lt;enumeration value="true"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="OtherFeatures" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FeaturesType", propOrder = {
    "featureSceneAccess",
    "featureCommentary",
    "featureTrailer",
    "featurePhotoGallery",
    "featureDeletedScenes",
    "featureMakingOf",
    "featureProductionNotes",
    "featureGame",
    "featureDVDROMContent",
    "featureMultiAngle",
    "featureMusicVideos",
    "featureInterviews",
    "featureStoryboardComparisons",
    "featureOuttakes",
    "featureClosedCaptioned",
    "featureTHXCertified",
    "featurePIP",
    "featureBDLive",
    "featureBonusTrailers",
    "featureDigitalCopy",
    "featureDBOX",
    "featureCineChat",
    "featurePlayAll",
    "featureMovieIQ",
    "otherFeatures"
})
public class FeaturesType {

    @XmlElement(name = "FeatureSceneAccess", required = true)
    protected String featureSceneAccess;
    @XmlElement(name = "FeatureCommentary", required = true)
    protected String featureCommentary;
    @XmlElement(name = "FeatureTrailer", required = true)
    protected String featureTrailer;
    @XmlElement(name = "FeaturePhotoGallery", required = true)
    protected String featurePhotoGallery;
    @XmlElement(name = "FeatureDeletedScenes", required = true)
    protected String featureDeletedScenes;
    @XmlElement(name = "FeatureMakingOf", required = true)
    protected String featureMakingOf;
    @XmlElement(name = "FeatureProductionNotes", required = true)
    protected String featureProductionNotes;
    @XmlElement(name = "FeatureGame", required = true)
    protected String featureGame;
    @XmlElement(name = "FeatureDVDROMContent", required = true)
    protected String featureDVDROMContent;
    @XmlElement(name = "FeatureMultiAngle", required = true)
    protected String featureMultiAngle;
    @XmlElement(name = "FeatureMusicVideos", required = true)
    protected String featureMusicVideos;
    @XmlElement(name = "FeatureInterviews", required = true)
    protected String featureInterviews;
    @XmlElement(name = "FeatureStoryboardComparisons", required = true)
    protected String featureStoryboardComparisons;
    @XmlElement(name = "FeatureOuttakes", required = true)
    protected String featureOuttakes;
    @XmlElement(name = "FeatureClosedCaptioned", required = true)
    protected String featureClosedCaptioned;
    @XmlElement(name = "FeatureTHXCertified", required = true)
    protected String featureTHXCertified;
    @XmlElement(name = "FeaturePIP", required = true)
    protected String featurePIP;
    @XmlElement(name = "FeatureBDLive", required = true)
    protected String featureBDLive;
    @XmlElement(name = "FeatureBonusTrailers", required = true)
    protected String featureBonusTrailers;
    @XmlElement(name = "FeatureDigitalCopy", required = true)
    protected String featureDigitalCopy;
    @XmlElement(name = "FeatureDBOX", required = true)
    protected String featureDBOX;
    @XmlElement(name = "FeatureCineChat", required = true)
    protected String featureCineChat;
    @XmlElement(name = "FeaturePlayAll", required = true)
    protected String featurePlayAll;
    @XmlElement(name = "FeatureMovieIQ", required = true)
    protected String featureMovieIQ;
    @XmlElement(name = "OtherFeatures", required = true)
    protected String otherFeatures;

    /**
     * Gets the value of the featureSceneAccess property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFeatureSceneAccess() {
        return featureSceneAccess;
    }

    /**
     * Sets the value of the featureSceneAccess property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFeatureSceneAccess(String value) {
        this.featureSceneAccess = value;
    }

    /**
     * Gets the value of the featureCommentary property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFeatureCommentary() {
        return featureCommentary;
    }

    /**
     * Sets the value of the featureCommentary property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFeatureCommentary(String value) {
        this.featureCommentary = value;
    }

    /**
     * Gets the value of the featureTrailer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFeatureTrailer() {
        return featureTrailer;
    }

    /**
     * Sets the value of the featureTrailer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFeatureTrailer(String value) {
        this.featureTrailer = value;
    }

    /**
     * Gets the value of the featurePhotoGallery property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFeaturePhotoGallery() {
        return featurePhotoGallery;
    }

    /**
     * Sets the value of the featurePhotoGallery property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFeaturePhotoGallery(String value) {
        this.featurePhotoGallery = value;
    }

    /**
     * Gets the value of the featureDeletedScenes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFeatureDeletedScenes() {
        return featureDeletedScenes;
    }

    /**
     * Sets the value of the featureDeletedScenes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFeatureDeletedScenes(String value) {
        this.featureDeletedScenes = value;
    }

    /**
     * Gets the value of the featureMakingOf property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFeatureMakingOf() {
        return featureMakingOf;
    }

    /**
     * Sets the value of the featureMakingOf property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFeatureMakingOf(String value) {
        this.featureMakingOf = value;
    }

    /**
     * Gets the value of the featureProductionNotes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFeatureProductionNotes() {
        return featureProductionNotes;
    }

    /**
     * Sets the value of the featureProductionNotes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFeatureProductionNotes(String value) {
        this.featureProductionNotes = value;
    }

    /**
     * Gets the value of the featureGame property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFeatureGame() {
        return featureGame;
    }

    /**
     * Sets the value of the featureGame property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFeatureGame(String value) {
        this.featureGame = value;
    }

    /**
     * Gets the value of the featureDVDROMContent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFeatureDVDROMContent() {
        return featureDVDROMContent;
    }

    /**
     * Sets the value of the featureDVDROMContent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFeatureDVDROMContent(String value) {
        this.featureDVDROMContent = value;
    }

    /**
     * Gets the value of the featureMultiAngle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFeatureMultiAngle() {
        return featureMultiAngle;
    }

    /**
     * Sets the value of the featureMultiAngle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFeatureMultiAngle(String value) {
        this.featureMultiAngle = value;
    }

    /**
     * Gets the value of the featureMusicVideos property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFeatureMusicVideos() {
        return featureMusicVideos;
    }

    /**
     * Sets the value of the featureMusicVideos property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFeatureMusicVideos(String value) {
        this.featureMusicVideos = value;
    }

    /**
     * Gets the value of the featureInterviews property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFeatureInterviews() {
        return featureInterviews;
    }

    /**
     * Sets the value of the featureInterviews property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFeatureInterviews(String value) {
        this.featureInterviews = value;
    }

    /**
     * Gets the value of the featureStoryboardComparisons property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFeatureStoryboardComparisons() {
        return featureStoryboardComparisons;
    }

    /**
     * Sets the value of the featureStoryboardComparisons property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFeatureStoryboardComparisons(String value) {
        this.featureStoryboardComparisons = value;
    }

    /**
     * Gets the value of the featureOuttakes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFeatureOuttakes() {
        return featureOuttakes;
    }

    /**
     * Sets the value of the featureOuttakes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFeatureOuttakes(String value) {
        this.featureOuttakes = value;
    }

    /**
     * Gets the value of the featureClosedCaptioned property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFeatureClosedCaptioned() {
        return featureClosedCaptioned;
    }

    /**
     * Sets the value of the featureClosedCaptioned property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFeatureClosedCaptioned(String value) {
        this.featureClosedCaptioned = value;
    }

    /**
     * Gets the value of the featureTHXCertified property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFeatureTHXCertified() {
        return featureTHXCertified;
    }

    /**
     * Sets the value of the featureTHXCertified property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFeatureTHXCertified(String value) {
        this.featureTHXCertified = value;
    }

    /**
     * Gets the value of the featurePIP property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFeaturePIP() {
        return featurePIP;
    }

    /**
     * Sets the value of the featurePIP property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFeaturePIP(String value) {
        this.featurePIP = value;
    }

    /**
     * Gets the value of the featureBDLive property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFeatureBDLive() {
        return featureBDLive;
    }

    /**
     * Sets the value of the featureBDLive property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFeatureBDLive(String value) {
        this.featureBDLive = value;
    }

    /**
     * Gets the value of the featureBonusTrailers property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFeatureBonusTrailers() {
        return featureBonusTrailers;
    }

    /**
     * Sets the value of the featureBonusTrailers property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFeatureBonusTrailers(String value) {
        this.featureBonusTrailers = value;
    }

    /**
     * Gets the value of the featureDigitalCopy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFeatureDigitalCopy() {
        return featureDigitalCopy;
    }

    /**
     * Sets the value of the featureDigitalCopy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFeatureDigitalCopy(String value) {
        this.featureDigitalCopy = value;
    }

    /**
     * Gets the value of the featureDBOX property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFeatureDBOX() {
        return featureDBOX;
    }

    /**
     * Sets the value of the featureDBOX property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFeatureDBOX(String value) {
        this.featureDBOX = value;
    }

    /**
     * Gets the value of the featureCineChat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFeatureCineChat() {
        return featureCineChat;
    }

    /**
     * Sets the value of the featureCineChat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFeatureCineChat(String value) {
        this.featureCineChat = value;
    }

    /**
     * Gets the value of the featurePlayAll property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFeaturePlayAll() {
        return featurePlayAll;
    }

    /**
     * Sets the value of the featurePlayAll property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFeaturePlayAll(String value) {
        this.featurePlayAll = value;
    }

    /**
     * Gets the value of the featureMovieIQ property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFeatureMovieIQ() {
        return featureMovieIQ;
    }

    /**
     * Sets the value of the featureMovieIQ property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFeatureMovieIQ(String value) {
        this.featureMovieIQ = value;
    }

    /**
     * Gets the value of the otherFeatures property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtherFeatures() {
        return otherFeatures;
    }

    /**
     * Sets the value of the otherFeatures property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtherFeatures(String value) {
        this.otherFeatures = value;
    }

}
