//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.24 at 11:58:45 PM CEST 
//


package no.smeaworks.movies.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FormatType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FormatType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FormatAspectRatio" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="FormatVideoStandard">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="NTSC"/>
 *               &lt;enumeration value="PAL"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ColorFormat" type="{}ColorFormatType"/>
 *         &lt;element name="DynamicRange" type="{}DynamicRangeType" minOccurs="0"/>
 *         &lt;element name="FormatLetterBox">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="true"/>
 *               &lt;enumeration value="false"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="FormatPanAndScan">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="false"/>
 *               &lt;enumeration value="true"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="FormatFullFrame">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="false"/>
 *               &lt;enumeration value="true"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Format16X9">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="false"/>
 *               &lt;enumeration value="true"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="FormatDualSided">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="false"/>
 *               &lt;enumeration value="true"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="FormatDualLayered">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="false"/>
 *               &lt;enumeration value="true"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Dimensions" type="{}DimensionsType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FormatType", propOrder = {
    "formatAspectRatio",
    "formatVideoStandard",
    "colorFormat",
    "dynamicRange",
    "formatLetterBox",
    "formatPanAndScan",
    "formatFullFrame",
    "format16X9",
    "formatDualSided",
    "formatDualLayered",
    "dimensions"
})
public class FormatType {

    @XmlElement(name = "FormatAspectRatio", required = true)
    protected String formatAspectRatio;
    @XmlElement(name = "FormatVideoStandard", required = true)
    protected String formatVideoStandard;
    @XmlElement(name = "ColorFormat", required = true)
    protected ColorFormatType colorFormat;
    @XmlElement(name = "DynamicRange")
    protected DynamicRangeType dynamicRange;
    @XmlElement(name = "FormatLetterBox", required = true)
    protected String formatLetterBox;
    @XmlElement(name = "FormatPanAndScan", required = true)
    protected String formatPanAndScan;
    @XmlElement(name = "FormatFullFrame", required = true)
    protected String formatFullFrame;
    @XmlElement(name = "Format16X9", required = true)
    protected String format16X9;
    @XmlElement(name = "FormatDualSided", required = true)
    protected String formatDualSided;
    @XmlElement(name = "FormatDualLayered", required = true)
    protected String formatDualLayered;
    @XmlElement(name = "Dimensions", required = true)
    protected DimensionsType dimensions;

    /**
     * Gets the value of the formatAspectRatio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormatAspectRatio() {
        return formatAspectRatio;
    }

    /**
     * Sets the value of the formatAspectRatio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormatAspectRatio(String value) {
        this.formatAspectRatio = value;
    }

    /**
     * Gets the value of the formatVideoStandard property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormatVideoStandard() {
        return formatVideoStandard;
    }

    /**
     * Sets the value of the formatVideoStandard property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormatVideoStandard(String value) {
        this.formatVideoStandard = value;
    }

    /**
     * Gets the value of the colorFormat property.
     * 
     * @return
     *     possible object is
     *     {@link ColorFormatType }
     *     
     */
    public ColorFormatType getColorFormat() {
        return colorFormat;
    }

    /**
     * Sets the value of the colorFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link ColorFormatType }
     *     
     */
    public void setColorFormat(ColorFormatType value) {
        this.colorFormat = value;
    }

    /**
     * Gets the value of the dynamicRange property.
     * 
     * @return
     *     possible object is
     *     {@link DynamicRangeType }
     *     
     */
    public DynamicRangeType getDynamicRange() {
        return dynamicRange;
    }

    /**
     * Sets the value of the dynamicRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link DynamicRangeType }
     *     
     */
    public void setDynamicRange(DynamicRangeType value) {
        this.dynamicRange = value;
    }

    /**
     * Gets the value of the formatLetterBox property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormatLetterBox() {
        return formatLetterBox;
    }

    /**
     * Sets the value of the formatLetterBox property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormatLetterBox(String value) {
        this.formatLetterBox = value;
    }

    /**
     * Gets the value of the formatPanAndScan property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormatPanAndScan() {
        return formatPanAndScan;
    }

    /**
     * Sets the value of the formatPanAndScan property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormatPanAndScan(String value) {
        this.formatPanAndScan = value;
    }

    /**
     * Gets the value of the formatFullFrame property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormatFullFrame() {
        return formatFullFrame;
    }

    /**
     * Sets the value of the formatFullFrame property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormatFullFrame(String value) {
        this.formatFullFrame = value;
    }

    /**
     * Gets the value of the format16X9 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormat16X9() {
        return format16X9;
    }

    /**
     * Sets the value of the format16X9 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormat16X9(String value) {
        this.format16X9 = value;
    }

    /**
     * Gets the value of the formatDualSided property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormatDualSided() {
        return formatDualSided;
    }

    /**
     * Sets the value of the formatDualSided property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormatDualSided(String value) {
        this.formatDualSided = value;
    }

    /**
     * Gets the value of the formatDualLayered property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormatDualLayered() {
        return formatDualLayered;
    }

    /**
     * Sets the value of the formatDualLayered property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormatDualLayered(String value) {
        this.formatDualLayered = value;
    }

    /**
     * Gets the value of the dimensions property.
     * 
     * @return
     *     possible object is
     *     {@link DimensionsType }
     *     
     */
    public DimensionsType getDimensions() {
        return dimensions;
    }

    /**
     * Sets the value of the dimensions property.
     * 
     * @param value
     *     allowed object is
     *     {@link DimensionsType }
     *     
     */
    public void setDimensions(DimensionsType value) {
        this.dimensions = value;
    }

}
