//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.24 at 11:58:45 PM CEST 
//


package no.smeaworks.movies.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MediaTypesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MediaTypesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DVD">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="false"/>
 *               &lt;enumeration value="true"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="HDDVD" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BluRay">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="true"/>
 *               &lt;enumeration value="false"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="UltraHD">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="false"/>
 *               &lt;enumeration value="true"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MediaTypesType", propOrder = {
    "dvd",
    "hddvd",
    "bluRay",
    "ultraHD"
})
public class MediaTypesType {

    @XmlElement(name = "DVD", required = true)
    protected String dvd;
    @XmlElement(name = "HDDVD", required = true)
    protected String hddvd;
    @XmlElement(name = "BluRay", required = true)
    protected String bluRay;
    @XmlElement(name = "UltraHD", required = true)
    protected String ultraHD;

    /**
     * Gets the value of the dvd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDVD() {
        return dvd;
    }

    /**
     * Sets the value of the dvd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDVD(String value) {
        this.dvd = value;
    }

    /**
     * Gets the value of the hddvd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHDDVD() {
        return hddvd;
    }

    /**
     * Sets the value of the hddvd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHDDVD(String value) {
        this.hddvd = value;
    }

    /**
     * Gets the value of the bluRay property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBluRay() {
        return bluRay;
    }

    /**
     * Sets the value of the bluRay property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBluRay(String value) {
        this.bluRay = value;
    }

    /**
     * Gets the value of the ultraHD property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUltraHD() {
        return ultraHD;
    }

    /**
     * Sets the value of the ultraHD property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUltraHD(String value) {
        this.ultraHD = value;
    }

}
