//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.24 at 11:58:45 PM CEST 
//


package no.smeaworks.movies.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the no.smeaworks.movies.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Collection_QNAME = new QName("", "Collection");
    private final static QName _GenresTypeGenre_QNAME = new QName("", "Genre");
    private final static QName _StudiosTypeStudio_QNAME = new QName("", "Studio");
    private final static QName _MediaCompaniesTypeMediaCompany_QNAME = new QName("", "MediaCompany");
    private final static QName _DVDTypeEventsEvent_QNAME = new QName("", "Event");
    private final static QName _BoxSetTypeContentsContent_QNAME = new QName("", "Content");
    private final static QName _AudioTypeAudioTrack_QNAME = new QName("", "AudioTrack");
    private final static QName _SubtitlesTypeSubtitle_QNAME = new QName("", "Subtitle");
    private final static QName _DVDTypeRegionsRegion_QNAME = new QName("", "Region");
    private final static QName _DiscsTypeDisc_QNAME = new QName("", "Disc");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: no.smeaworks.movies.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BoxSetType }
     * 
     */
    public BoxSetType createBoxSetType() {
        return new BoxSetType();
    }

    /**
     * Create an instance of {@link DVDType }
     * 
     */
    public DVDType createDVDType() {
        return new DVDType();
    }

    /**
     * Create an instance of {@link CollectionType }
     * 
     */
    public CollectionType createCollectionType() {
        return new CollectionType();
    }

    /**
     * Create an instance of {@link CollectionTypeType }
     * 
     */
    public CollectionTypeType createCollectionTypeType() {
        return new CollectionTypeType();
    }

    /**
     * Create an instance of {@link SubtitlesType }
     * 
     */
    public SubtitlesType createSubtitlesType() {
        return new SubtitlesType();
    }

    /**
     * Create an instance of {@link EventType }
     * 
     */
    public EventType createEventType() {
        return new EventType();
    }

    /**
     * Create an instance of {@link SRPType }
     * 
     */
    public SRPType createSRPType() {
        return new SRPType();
    }

    /**
     * Create an instance of {@link MediaBannersType }
     * 
     */
    public MediaBannersType createMediaBannersType() {
        return new MediaBannersType();
    }

    /**
     * Create an instance of {@link DiscType }
     * 
     */
    public DiscType createDiscType() {
        return new DiscType();
    }

    /**
     * Create an instance of {@link DiscsType }
     * 
     */
    public DiscsType createDiscsType() {
        return new DiscsType();
    }

    /**
     * Create an instance of {@link EventsType }
     * 
     */
    public EventsType createEventsType() {
        return new EventsType();
    }

    /**
     * Create an instance of {@link PurchaseInfoType }
     * 
     */
    public PurchaseInfoType createPurchaseInfoType() {
        return new PurchaseInfoType();
    }

    /**
     * Create an instance of {@link DynamicRangeType }
     * 
     */
    public DynamicRangeType createDynamicRangeType() {
        return new DynamicRangeType();
    }

    /**
     * Create an instance of {@link RegionsType }
     * 
     */
    public RegionsType createRegionsType() {
        return new RegionsType();
    }

    /**
     * Create an instance of {@link FeaturesType }
     * 
     */
    public FeaturesType createFeaturesType() {
        return new FeaturesType();
    }

    /**
     * Create an instance of {@link ReviewType }
     * 
     */
    public ReviewType createReviewType() {
        return new ReviewType();
    }

    /**
     * Create an instance of {@link AudioTrackType }
     * 
     */
    public AudioTrackType createAudioTrackType() {
        return new AudioTrackType();
    }

    /**
     * Create an instance of {@link StudiosType }
     * 
     */
    public StudiosType createStudiosType() {
        return new StudiosType();
    }

    /**
     * Create an instance of {@link FormatType }
     * 
     */
    public FormatType createFormatType() {
        return new FormatType();
    }

    /**
     * Create an instance of {@link ColorFormatType }
     * 
     */
    public ColorFormatType createColorFormatType() {
        return new ColorFormatType();
    }

    /**
     * Create an instance of {@link LoanInfoType }
     * 
     */
    public LoanInfoType createLoanInfoType() {
        return new LoanInfoType();
    }

    /**
     * Create an instance of {@link MediaTypesType }
     * 
     */
    public MediaTypesType createMediaTypesType() {
        return new MediaTypesType();
    }

    /**
     * Create an instance of {@link GenresType }
     * 
     */
    public GenresType createGenresType() {
        return new GenresType();
    }

    /**
     * Create an instance of {@link DimensionsType }
     * 
     */
    public DimensionsType createDimensionsType() {
        return new DimensionsType();
    }

    /**
     * Create an instance of {@link GiftFromType }
     * 
     */
    public GiftFromType createGiftFromType() {
        return new GiftFromType();
    }

    /**
     * Create an instance of {@link AudioType }
     * 
     */
    public AudioType createAudioType() {
        return new AudioType();
    }

    /**
     * Create an instance of {@link PurchasePriceType }
     * 
     */
    public PurchasePriceType createPurchasePriceType() {
        return new PurchasePriceType();
    }

    /**
     * Create an instance of {@link UserType }
     * 
     */
    public UserType createUserType() {
        return new UserType();
    }

    /**
     * Create an instance of {@link MediaCompaniesType }
     * 
     */
    public MediaCompaniesType createMediaCompaniesType() {
        return new MediaCompaniesType();
    }

    /**
     * Create an instance of {@link ContentsType }
     * 
     */
    public ContentsType createContentsType() {
        return new ContentsType();
    }

    /**
     * Create an instance of {@link BoxSetType.Contents }
     * 
     */
    public BoxSetType.Contents createBoxSetTypeContents() {
        return new BoxSetType.Contents();
    }

    /**
     * Create an instance of {@link DVDType.Regions }
     * 
     */
    public DVDType.Regions createDVDTypeRegions() {
        return new DVDType.Regions();
    }

    /**
     * Create an instance of {@link DVDType.Events }
     * 
     */
    public DVDType.Events createDVDTypeEvents() {
        return new DVDType.Events();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CollectionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Collection")
    public JAXBElement<CollectionType> createCollection(CollectionType value) {
        return new JAXBElement<CollectionType>(_Collection_QNAME, CollectionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Genre", scope = GenresType.class)
    public JAXBElement<String> createGenresTypeGenre(String value) {
        return new JAXBElement<String>(_GenresTypeGenre_QNAME, String.class, GenresType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Studio", scope = StudiosType.class)
    public JAXBElement<String> createStudiosTypeStudio(String value) {
        return new JAXBElement<String>(_StudiosTypeStudio_QNAME, String.class, StudiosType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MediaCompany", scope = MediaCompaniesType.class)
    public JAXBElement<String> createMediaCompaniesTypeMediaCompany(String value) {
        return new JAXBElement<String>(_MediaCompaniesTypeMediaCompany_QNAME, String.class, MediaCompaniesType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EventType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Event", scope = DVDType.Events.class)
    public JAXBElement<EventType> createDVDTypeEventsEvent(EventType value) {
        return new JAXBElement<EventType>(_DVDTypeEventsEvent_QNAME, EventType.class, DVDType.Events.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Content", scope = BoxSetType.Contents.class)
    public JAXBElement<String> createBoxSetTypeContentsContent(String value) {
        return new JAXBElement<String>(_BoxSetTypeContentsContent_QNAME, String.class, BoxSetType.Contents.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AudioTrackType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AudioTrack", scope = AudioType.class)
    public JAXBElement<AudioTrackType> createAudioTypeAudioTrack(AudioTrackType value) {
        return new JAXBElement<AudioTrackType>(_AudioTypeAudioTrack_QNAME, AudioTrackType.class, AudioType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Subtitle", scope = SubtitlesType.class)
    public JAXBElement<String> createSubtitlesTypeSubtitle(String value) {
        return new JAXBElement<String>(_SubtitlesTypeSubtitle_QNAME, String.class, SubtitlesType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Region", scope = DVDType.Regions.class)
    public JAXBElement<String> createDVDTypeRegionsRegion(String value) {
        return new JAXBElement<String>(_DVDTypeRegionsRegion_QNAME, String.class, DVDType.Regions.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DiscType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Disc", scope = DiscsType.class)
    public JAXBElement<DiscType> createDiscsTypeDisc(DiscType value) {
        return new JAXBElement<DiscType>(_DiscsTypeDisc_QNAME, DiscType.class, DiscsType.class, value);
    }

}
