//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.24 at 11:58:45 PM CEST 
//


package no.smeaworks.movies.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for PurchasePriceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PurchasePriceType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
 *       &lt;attribute name="DenominationType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="DenominationDesc" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="FormattedValue" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PurchasePriceType", propOrder = {
    "value"
})
public class PurchasePriceType {

    @XmlValue
    protected float value;
    @XmlAttribute(name = "DenominationType")
    protected String denominationType;
    @XmlAttribute(name = "DenominationDesc")
    protected String denominationDesc;
    @XmlAttribute(name = "FormattedValue")
    protected String formattedValue;

    /**
     * Gets the value of the value property.
     * 
     */
    public float getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     */
    public void setValue(float value) {
        this.value = value;
    }

    /**
     * Gets the value of the denominationType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDenominationType() {
        return denominationType;
    }

    /**
     * Sets the value of the denominationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDenominationType(String value) {
        this.denominationType = value;
    }

    /**
     * Gets the value of the denominationDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDenominationDesc() {
        return denominationDesc;
    }

    /**
     * Sets the value of the denominationDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDenominationDesc(String value) {
        this.denominationDesc = value;
    }

    /**
     * Gets the value of the formattedValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormattedValue() {
        return formattedValue;
    }

    /**
     * Sets the value of the formattedValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormattedValue(String value) {
        this.formattedValue = value;
    }

}
