//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.24 at 11:58:45 PM CEST 
//


package no.smeaworks.movies.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for PurchaseInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PurchaseInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PurchasePrice" type="{}PurchasePriceType"/>
 *         &lt;element name="PurchasePlace">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value=""/>
 *               &lt;enumeration value="Platekompaniet"/>
 *               &lt;enumeration value="Amazon"/>
 *               &lt;enumeration value="CDON"/>
 *               &lt;enumeration value="Playx"/>
 *               &lt;enumeration value="Videonova"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PurchasePlaceType">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value=""/>
 *               &lt;enumeration value="O"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PurchasePlaceWebsite">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value=""/>
 *               &lt;enumeration value="http://www.platekompaniet.no"/>
 *               &lt;enumeration value="https://www.amazon.co.uk"/>
 *               &lt;enumeration value="http://www.cdon.com"/>
 *               &lt;enumeration value="http://www.playx.no"/>
 *               &lt;enumeration value="http://www.videonova.no"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PurchaseDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="ReceivedAsGift" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="GiftFrom" type="{}GiftFromType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PurchaseInfoType", propOrder = {
    "purchasePrice",
    "purchasePlace",
    "purchasePlaceType",
    "purchasePlaceWebsite",
    "purchaseDate",
    "receivedAsGift",
    "giftFrom"
})
public class PurchaseInfoType {

    @XmlElement(name = "PurchasePrice", required = true)
    protected PurchasePriceType purchasePrice;
    @XmlElement(name = "PurchasePlace", required = true)
    protected String purchasePlace;
    @XmlElement(name = "PurchasePlaceType", required = true)
    protected String purchasePlaceType;
    @XmlElement(name = "PurchasePlaceWebsite", required = true)
    protected String purchasePlaceWebsite;
    @XmlElement(name = "PurchaseDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar purchaseDate;
    @XmlElement(name = "ReceivedAsGift", required = true)
    protected String receivedAsGift;
    @XmlElement(name = "GiftFrom", required = true)
    protected GiftFromType giftFrom;

    /**
     * Gets the value of the purchasePrice property.
     * 
     * @return
     *     possible object is
     *     {@link PurchasePriceType }
     *     
     */
    public PurchasePriceType getPurchasePrice() {
        return purchasePrice;
    }

    /**
     * Sets the value of the purchasePrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link PurchasePriceType }
     *     
     */
    public void setPurchasePrice(PurchasePriceType value) {
        this.purchasePrice = value;
    }

    /**
     * Gets the value of the purchasePlace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPurchasePlace() {
        return purchasePlace;
    }

    /**
     * Sets the value of the purchasePlace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPurchasePlace(String value) {
        this.purchasePlace = value;
    }

    /**
     * Gets the value of the purchasePlaceType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPurchasePlaceType() {
        return purchasePlaceType;
    }

    /**
     * Sets the value of the purchasePlaceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPurchasePlaceType(String value) {
        this.purchasePlaceType = value;
    }

    /**
     * Gets the value of the purchasePlaceWebsite property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPurchasePlaceWebsite() {
        return purchasePlaceWebsite;
    }

    /**
     * Sets the value of the purchasePlaceWebsite property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPurchasePlaceWebsite(String value) {
        this.purchasePlaceWebsite = value;
    }

    /**
     * Gets the value of the purchaseDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPurchaseDate() {
        return purchaseDate;
    }

    /**
     * Sets the value of the purchaseDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPurchaseDate(XMLGregorianCalendar value) {
        this.purchaseDate = value;
    }

    /**
     * Gets the value of the receivedAsGift property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReceivedAsGift() {
        return receivedAsGift;
    }

    /**
     * Sets the value of the receivedAsGift property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReceivedAsGift(String value) {
        this.receivedAsGift = value;
    }

    /**
     * Gets the value of the giftFrom property.
     * 
     * @return
     *     possible object is
     *     {@link GiftFromType }
     *     
     */
    public GiftFromType getGiftFrom() {
        return giftFrom;
    }

    /**
     * Sets the value of the giftFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link GiftFromType }
     *     
     */
    public void setGiftFrom(GiftFromType value) {
        this.giftFrom = value;
    }

}
